name = "fpx"
version = "1.0.0"
maintainer = "David Pfister"
author = "David Pfister"
description = "preprocessing app"
categories = ["preprocessing"]
keywords = ["preprocessing", "fpx"]
homepage = "https://github.com/davidpfister/fpx.f"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_WIN32", "_FPM"]

[library]
source-dir = "src"
include-dir = ["include"]

[install]
library = false

[fortran]
implicit-external = false

[[test]]
name = "test_arithmetic"
source-dir = "tests"
main = "test_arithmetic.f90"

[[test]]
name = "test_c"
source-dir = "tests"
main = "test_c.f90"

[[test]]
name = "test_cli"
source-dir = "tests"
main = "test_cli.f90"

[[test]]
name = "test_default"
source-dir = "tests"
main = "test_default.f90"

[[test]]
name = "test_flang"
source-dir = "tests"
main = "test_flang.f90"

[[test]]
name = "test_lfortran"
source-dir = "tests"
main = "test_lfortran.f90"

[extra.fortitude.check]
select = ["C", "E", "S"]
ignore = ["S001", "S061", "C121", "C003"]
line-length = 132
